# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/HighScreen/D10A_HighScreen/setup-makefiles.sh

VENDOR_PATH := vendor/HighScreen/D10A_HighScreen/proprietary

# app
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/app/qcrilmsgtunnel.apk:system/app/qcrilmsgtunnel.apk

# bin
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/bin/adsprpcd:system/bin/adsprpcd \
    $(VENDOR_PATH)/bin/applypatch:system/bin/applypatch \
    $(VENDOR_PATH)/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    $(VENDOR_PATH)/bin/brctl:system/bin/brctl \
    $(VENDOR_PATH)/bin/bridgemgrd:system/bin/bridgemgrd \
    $(VENDOR_PATH)/bin/btnvtool:system/bin/btnvtool \
    $(VENDOR_PATH)/bin/charger_monitor:system/bin/charger_monitor \
    $(VENDOR_PATH)/bin/cnd:system/bin/cnd \
    $(VENDOR_PATH)/bin/diag_callback_client:system/bin/diag_callback_client \
    $(VENDOR_PATH)/bin/diag_dci_sample:system/bin/diag_dci_sample \
    $(VENDOR_PATH)/bin/diag_klog:system/bin/diag_klog \
    $(VENDOR_PATH)/bin/diag_mdlog:system/bin/diag_mdlog \
    $(VENDOR_PATH)/bin/diag_socket_log:system/bin/diag_socket_log \
    $(VENDOR_PATH)/bin/diag_uart_log:system/bin/diag_uart_log \
    $(VENDOR_PATH)/bin/drmdiagapp:system/bin/drmdiagapp \
    $(VENDOR_PATH)/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    $(VENDOR_PATH)/bin/flatland:system/bin/flatland \
    $(VENDOR_PATH)/bin/fmconfig:system/bin/fmconfig \
    $(VENDOR_PATH)/bin/fmfactorytest:system/bin/fmfactorytest \
    $(VENDOR_PATH)/bin/fmfactorytestserver:system/bin/fmfactorytestserver \
    $(VENDOR_PATH)/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    $(VENDOR_PATH)/bin/ftmdaemon:system/bin/ftmdaemon \
    $(VENDOR_PATH)/bin/garden_app:system/bin/garden_app \
    $(VENDOR_PATH)/bin/gpsone_daemon:system/bin/gpsone_daemon \
    $(VENDOR_PATH)/bin/gsiff_daemon:system/bin/gsiff_daemon \
    $(VENDOR_PATH)/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(VENDOR_PATH)/bin/hvdcp:system/bin/hvdcp \
    $(VENDOR_PATH)/bin/imsdatadaemon:system/bin/imsdatadaemon \
    $(VENDOR_PATH)/bin/imsqmidaemon:system/bin/imsqmidaemon \
    $(VENDOR_PATH)/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    $(VENDOR_PATH)/bin/irsc_util:system/bin/irsc_util \
    $(VENDOR_PATH)/bin/isdbtmmtest:system/bin/isdbtmmtest \
    $(VENDOR_PATH)/bin/location-mq:system/bin/location-mq \
    $(VENDOR_PATH)/bin/lowi-server:system/bin/lowi-server \
    $(VENDOR_PATH)/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    $(VENDOR_PATH)/bin/mcStarter:system/bin/mcStarter \
    $(VENDOR_PATH)/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    $(VENDOR_PATH)/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    $(VENDOR_PATH)/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    $(VENDOR_PATH)/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    $(VENDOR_PATH)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(VENDOR_PATH)/bin/mm-qjpeg-dec-test:system/bin/mm-qjpeg-dec-test \
    $(VENDOR_PATH)/bin/mm-qjpeg-enc-test:system/bin/mm-qjpeg-enc-test \
    $(VENDOR_PATH)/bin/mm-qomx-idec-test:system/bin/mm-qomx-idec-test \
    $(VENDOR_PATH)/bin/mm-qomx-ienc-test:system/bin/mm-qomx-ienc-test \
    $(VENDOR_PATH)/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    $(VENDOR_PATH)/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    $(VENDOR_PATH)/bin/mm-video-driver-test:system/bin/mm-video-driver-test \
    $(VENDOR_PATH)/bin/mm-video-encdrv-test:system/bin/mm-video-encdrv-test \
    $(VENDOR_PATH)/bin/mmi:system/bin/mmi \
    $(VENDOR_PATH)/bin/mpdecision:system/bin/mpdecision \
    $(VENDOR_PATH)/bin/netmgrd:system/bin/netmgrd \
    $(VENDOR_PATH)/bin/nl_listener:system/bin/nl_listener \
    $(VENDOR_PATH)/bin/PktRspTest:system/bin/PktRspTest \
    $(VENDOR_PATH)/bin/port-bridge:system/bin/port-bridge \
    $(VENDOR_PATH)/bin/ptt_socket_app:system/bin/ptt_socket_app \
    $(VENDOR_PATH)/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    $(VENDOR_PATH)/bin/qmiproxy:system/bin/qmiproxy \
    $(VENDOR_PATH)/bin/qmuxd:system/bin/qmuxd \
    $(VENDOR_PATH)/bin/qseecomd:system/bin/qseecomd \
    $(VENDOR_PATH)/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    $(VENDOR_PATH)/bin/qseecom_security_test:system/bin/qseecom_security_test \
    $(VENDOR_PATH)/bin/quipc_igsn:system/bin/quipc_igsn \
    $(VENDOR_PATH)/bin/quipc_main:system/bin/quipc_main \
    $(VENDOR_PATH)/bin/radish:system/bin/radish \
    $(VENDOR_PATH)/bin/rfs_access:system/bin/rfs_access \
    $(VENDOR_PATH)/bin/rmt_storage:system/bin/rmt_storage \
    $(VENDOR_PATH)/bin/sapd:system/bin/sapd \
    $(VENDOR_PATH)/bin/sensors.qcom:system/bin/sensors.qcom \
    $(VENDOR_PATH)/bin/ssr_diag:system/bin/ssr_diag \
    $(VENDOR_PATH)/bin/StoreKeybox:system/bin/StoreKeybox \
    $(VENDOR_PATH)/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    $(VENDOR_PATH)/bin/system_server:system/bin/system_server \
    $(VENDOR_PATH)/bin/test_diag:system/bin/test_diag \
    $(VENDOR_PATH)/bin/thermal-engine:system/bin/thermal-engine \
    $(VENDOR_PATH)/bin/time_daemon:system/bin/time_daemon \
    $(VENDOR_PATH)/bin/tlcWrapperApp:system/bin/tlcWrapperApp \
    $(VENDOR_PATH)/bin/usbhub:system/bin/usbhub \
    $(VENDOR_PATH)/bin/usbhub_init:system/bin/usbhub_init \
    $(VENDOR_PATH)/bin/wcnss_service:system/bin/wcnss_service \
    $(VENDOR_PATH)/bin/wdsdaemon:system/bin/wdsdaemon \
    $(VENDOR_PATH)/bin/xtwifi-client:system/bin/xtwifi-client \
    $(VENDOR_PATH)/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent

# etc
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    $(VENDOR_PATH)/etc/General_cal.acdb:system/etc/General_cal.acdb \
    $(VENDOR_PATH)/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    $(VENDOR_PATH)/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    $(VENDOR_PATH)/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    $(VENDOR_PATH)/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    $(VENDOR_PATH)/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    $(VENDOR_PATH)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(VENDOR_PATH)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(VENDOR_PATH)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(VENDOR_PATH)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(VENDOR_PATH)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(VENDOR_PATH)/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(VENDOR_PATH)/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(VENDOR_PATH)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(VENDOR_PATH)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(VENDOR_PATH)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(VENDOR_PATH)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(VENDOR_PATH)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(VENDOR_PATH)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(VENDOR_PATH)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(VENDOR_PATH)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(VENDOR_PATH)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(VENDOR_PATH)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(VENDOR_PATH)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(VENDOR_PATH)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(VENDOR_PATH)/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml

# Framework
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/framework/qcrilhook.jar:system/framework/qcrilhook.jar

# lib
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
    $(VENDOR_PATH)/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    $(VENDOR_PATH)/lib/libfrsdk.so:system/lib/libfrsdk.so \
    $(VENDOR_PATH)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(VENDOR_PATH)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(VENDOR_PATH)/lib/libloc_core.so:system/lib/libloc_core.so \
    $(VENDOR_PATH)/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    $(VENDOR_PATH)/lib/libloc_eng.so:system/lib/libloc_eng.so \
    $(VENDOR_PATH)/lib/libloc_xtra.so:system/lib/libloc_xtra.so \
    $(VENDOR_PATH)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(VENDOR_PATH)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(VENDOR_PATH)/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    $(VENDOR_PATH)/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    $(VENDOR_PATH)/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(VENDOR_PATH)/lib/libril.so:system/lib/libril.so

#    $(VENDOR_PATH)/lib/libreference-ril.so:system/lib/libreference-ril.so \
#    $(VENDOR_PATH)/lib/librilutils.so:system/lib/librilutils.so

# lib/hw
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    $(VENDOR_PATH)/lib/hw/power.default.so:system/lib/hw/power.default.so

# lib/modules
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/lib/modules/pronto/pronto_wlan.ko:system/lib/modules/pronto/pronto_wlan.ko \
    $(VENDOR_PATH)/lib/modules/adsprpc.ko:system/lib/modules/adsprpc.ko \
    $(VENDOR_PATH)/lib/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
    $(VENDOR_PATH)/lib/modules/coresight-event.ko:system/lib/modules/coresight-event.ko \
    $(VENDOR_PATH)/lib/modules/dma_test.ko:system/lib/modules/dma_test.ko\
    $(VENDOR_PATH)/lib/modules/evbug.ko:system/lib/modules/evbug.ko \
    $(VENDOR_PATH)/lib/modules/gpio_axis.ko:system/lib/modules/gpio_axis.ko \
    $(VENDOR_PATH)/lib/modules/gpio_event.ko:system/lib/modules/gpio_event.ko \
    $(VENDOR_PATH)/lib/modules/gpio_input.ko:system/lib/modules/gpio_input.ko \
    $(VENDOR_PATH)/lib/modules/gpio_matrix.ko:system/lib/modules/gpio_matrix.ko \
    $(VENDOR_PATH)/lib/modules/gpio_output.ko:system/lib/modules/gpio_output.ko \
    $(VENDOR_PATH)/lib/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
    $(VENDOR_PATH)/lib/modules/mcdrvmodule.ko:system/lib/modules/mcdrvmodule.ko \
    $(VENDOR_PATH)/lib/modules/mckernelapi.ko:system/lib/modules/mckernelapi.ko \
    $(VENDOR_PATH)/lib/modules/mmc_block_test.ko:system/lib/modules/mmc_block_test.ko \
    $(VENDOR_PATH)/lib/modules/mmc_test.ko:system/lib/modules/mmc_test.ko \
    $(VENDOR_PATH)/lib/modules/msm-buspm-dev.ko:system/lib/modules/msm-buspm-dev.ko \
    $(VENDOR_PATH)/lib/modules/oprofile.ko:system/lib/modules/oprofile.ko \
    $(VENDOR_PATH)/lib/modules/qcedev.ko:system/lib/modules/qcedev.ko \
    $(VENDOR_PATH)/lib/modules/qcrypto.ko:system/lib/modules/qcrypto.ko\
    $(VENDOR_PATH)/lib/modules/radio-iris-transport.ko:system/lib/modules/radio-iris-transport.ko \
    $(VENDOR_PATH)/lib/modules/reset_modem.ko:system/lib/modules/reset_modem.ko \
    $(VENDOR_PATH)/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    $(VENDOR_PATH)/lib/modules/spidev.ko:system/lib/modules/spidev.ko \
    $(VENDOR_PATH)/lib/modules/test-iosched.ko:system/lib/modules/test-iosched.ko\

# vendor/default
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/Default/system/etc/apns-conf.xml:system/vendor/Default/system/etc/apns-conf.xml \
    $(VENDOR_PATH)/vendor/Default/system/etc/cdma_call_conf.xml:system/vendor/Default/system/etc/cdma_call_conf.xml \
    $(VENDOR_PATH)/vendor/Default/system/etc/spn-conf.xml:system/vendor/Default/system/etc/spn-conf.xml

# vendor/lib/drm
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so

# vendor/lib/rfsa/adsp
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    $(VENDOR_PATH)/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    $(VENDOR_PATH)/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    $(VENDOR_PATH)/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(VENDOR_PATH)/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# vendor/lib
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(VENDOR_PATH)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(VENDOR_PATH)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(VENDOR_PATH)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(VENDOR_PATH)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(VENDOR_PATH)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(VENDOR_PATH)/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(VENDOR_PATH)/vendor/lib/libalsautils.so:system/vendor/lib/libalsautils.so \
    $(VENDOR_PATH)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(VENDOR_PATH)/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(VENDOR_PATH)/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    $(VENDOR_PATH)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(VENDOR_PATH)/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    $(VENDOR_PATH)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(VENDOR_PATH)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(VENDOR_PATH)/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    $(VENDOR_PATH)/vendor/lib/libcamerahandler_jni.so:system/vendor/lib/libcamerahandler_jni.so \
    $(VENDOR_PATH)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_t4k37ab_common.so:system/vendor/lib/libchromatix_t4k37ab_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_t4k37ab_default_video.so:system/vendor/lib/libchromatix_t4k37ab_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_t4k37ab_preview.so:system/vendor/lib/libchromatix_t4k37ab_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_t4k37ab_snapshot.so:system/vendor/lib/libchromatix_t4k37ab_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_tcm9516md_common.so:system/vendor/lib/libchromatix_tcm9516md_common.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_tcm9516md_default_video.so:system/vendor/lib/libchromatix_tcm9516md_default_video.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_tcm9516md_liveshot.so:system/vendor/lib/libchromatix_tcm9516md_liveshot.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_tcm9516md_preview.so:system/vendor/lib/libchromatix_tcm9516md_preview.so \
    $(VENDOR_PATH)/vendor/lib/libchromatix_tcm9516md_snapshot.so:system/vendor/lib/libchromatix_tcm9516md_snapshot.so \
    $(VENDOR_PATH)/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(VENDOR_PATH)/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    $(VENDOR_PATH)/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(VENDOR_PATH)/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
    $(VENDOR_PATH)/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    $(VENDOR_PATH)/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(VENDOR_PATH)/vendor/lib/libcsd-client.so:system/vendor/lib/libcsd-client.so \
    $(VENDOR_PATH)/vendor/lib/libcsvt_jni.so:system/vendor/lib/libcsvt_jni.so \
    $(VENDOR_PATH)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(VENDOR_PATH)/vendor/lib/libDiagService.so:system/vendor/lib/libDiagService.so \
    $(VENDOR_PATH)/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(VENDOR_PATH)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(VENDOR_PATH)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(VENDOR_PATH)/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    $(VENDOR_PATH)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(VENDOR_PATH)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(VENDOR_PATH)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(VENDOR_PATH)/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    $(VENDOR_PATH)/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
    $(VENDOR_PATH)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(VENDOR_PATH)/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    $(VENDOR_PATH)/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    $(VENDOR_PATH)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(VENDOR_PATH)/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(VENDOR_PATH)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(VENDOR_PATH)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(VENDOR_PATH)/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    $(VENDOR_PATH)/vendor/lib/libhscdtd.so:system/vendor/lib/libhscdtd.so \
    $(VENDOR_PATH)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(VENDOR_PATH)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    $(VENDOR_PATH)/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    $(VENDOR_PATH)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(VENDOR_PATH)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(VENDOR_PATH)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(VENDOR_PATH)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(VENDOR_PATH)/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    $(VENDOR_PATH)/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    $(VENDOR_PATH)/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(VENDOR_PATH)/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    $(VENDOR_PATH)/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
    $(VENDOR_PATH)/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(VENDOR_PATH)/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    $(VENDOR_PATH)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(VENDOR_PATH)/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_f4k37ab_qtech_t4k37_eeprom.so:system/vendor/lib/libmmcamera_f4k37ab_qtech_t4k37_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_t4k37ab.so:system/vendor/lib/libmmcamera_t4k37ab.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_tcm9516md.so:system/vendor/lib/libmmcamera_tcm9516md.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(VENDOR_PATH)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(VENDOR_PATH)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(VENDOR_PATH)/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    $(VENDOR_PATH)/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    $(VENDOR_PATH)/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    $(VENDOR_PATH)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(VENDOR_PATH)/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    $(VENDOR_PATH)/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    $(VENDOR_PATH)/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    $(VENDOR_PATH)/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    $(VENDOR_PATH)/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
    $(VENDOR_PATH)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(VENDOR_PATH)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(VENDOR_PATH)/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    $(VENDOR_PATH)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(VENDOR_PATH)/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    $(VENDOR_PATH)/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
    $(VENDOR_PATH)/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    $(VENDOR_PATH)/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    $(VENDOR_PATH)/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    $(VENDOR_PATH)/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    $(VENDOR_PATH)/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
    $(VENDOR_PATH)/vendor/lib/libmsapm_jni.so:system/vendor/lib/libmsapm_jni.so \
    $(VENDOR_PATH)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(VENDOR_PATH)/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(VENDOR_PATH)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(VENDOR_PATH)/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    $(VENDOR_PATH)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(VENDOR_PATH)/vendor/lib/libomx_amrdec_sharedlibrary.so:system/vendor/lib/libomx_amrdec_sharedlibrary.so \
    $(VENDOR_PATH)/vendor/lib/libomx_amrenc_sharedlibrary.so:system/vendor/lib/libomx_amrenc_sharedlibrary.so \
    $(VENDOR_PATH)/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    $(VENDOR_PATH)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(VENDOR_PATH)/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(VENDOR_PATH)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(VENDOR_PATH)/vendor/lib/libomx_sharedlibrary.so:system/vendor/lib/libomx_sharedlibrary.so \
    $(VENDOR_PATH)/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    $(VENDOR_PATH)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(VENDOR_PATH)/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    $(VENDOR_PATH)/vendor/lib/libP11Notify.so:system/vendor/lib/libP11Notify.so \
    $(VENDOR_PATH)/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
    $(VENDOR_PATH)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(VENDOR_PATH)/vendor/lib/libqcom_omx.so:system/vendor/lib/libqcom_omx.so \
    $(VENDOR_PATH)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(VENDOR_PATH)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(VENDOR_PATH)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    $(VENDOR_PATH)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(VENDOR_PATH)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(VENDOR_PATH)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(VENDOR_PATH)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(VENDOR_PATH)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(VENDOR_PATH)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(VENDOR_PATH)/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(VENDOR_PATH)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(VENDOR_PATH)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(VENDOR_PATH)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(VENDOR_PATH)/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(VENDOR_PATH)/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(VENDOR_PATH)/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(VENDOR_PATH)/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(VENDOR_PATH)/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    $(VENDOR_PATH)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(VENDOR_PATH)/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(VENDOR_PATH)/vendor/lib/libSecureTouchPerfApp.so:system/vendor/lib/libSecureTouchPerfApp.so \
    $(VENDOR_PATH)/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    $(VENDOR_PATH)/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    $(VENDOR_PATH)/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
    $(VENDOR_PATH)/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so \
    $(VENDOR_PATH)/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    $(VENDOR_PATH)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(VENDOR_PATH)/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    $(VENDOR_PATH)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(VENDOR_PATH)/vendor/lib/libSSEPKCS11.so:system/vendor/lib/libSSEPKCS11.so \
    $(VENDOR_PATH)/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    $(VENDOR_PATH)/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    $(VENDOR_PATH)/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    $(VENDOR_PATH)/vendor/lib/libsurround_proc.so:system/vendor/lib/libsurround_proc.so \
    $(VENDOR_PATH)/vendor/lib/libswdec_2dto3d.so:system/vendor/lib/libswdec_2dto3d.so \
    $(VENDOR_PATH)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(VENDOR_PATH)/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(VENDOR_PATH)/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so \
    $(VENDOR_PATH)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(VENDOR_PATH)/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(VENDOR_PATH)/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    $(VENDOR_PATH)/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(VENDOR_PATH)/vendor/lib/libv8.so:system/vendor/lib/libv8.so \
    $(VENDOR_PATH)/vendor/lib/libvt_engine.so:system/vendor/lib/libvt_engine.so \
    $(VENDOR_PATH)/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    $(VENDOR_PATH)/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    $(VENDOR_PATH)/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    $(VENDOR_PATH)/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    $(VENDOR_PATH)/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    $(VENDOR_PATH)/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    $(VENDOR_PATH)/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    $(VENDOR_PATH)/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    $(VENDOR_PATH)/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    $(VENDOR_PATH)/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    $(VENDOR_PATH)/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    $(VENDOR_PATH)/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    $(VENDOR_PATH)/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    $(VENDOR_PATH)/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(VENDOR_PATH)/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    $(VENDOR_PATH)/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    $(VENDOR_PATH)/vendor/lib/libyas530.so:system/vendor/lib/libyas530.so \
    $(VENDOR_PATH)/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
    $(VENDOR_PATH)/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
    $(VENDOR_PATH)/vendor/lib/mmi_bt.so:system/vendor/lib/mmi_bt.so \
    $(VENDOR_PATH)/vendor/lib/mmi_camera.so:system/vendor/lib/mmi_camera.so \
    $(VENDOR_PATH)/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
    $(VENDOR_PATH)/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
    $(VENDOR_PATH)/vendor/lib/mmi_gps_garden.so:system/vendor/lib/mmi_gps_garden.so \
    $(VENDOR_PATH)/vendor/lib/mmi_gsensor.so:system/vendor/lib/mmi_gsensor.so \
    $(VENDOR_PATH)/vendor/lib/mmi_gyroscope.so:system/vendor/lib/mmi_gyroscope.so \
    $(VENDOR_PATH)/vendor/lib/mmi_keypadbacklight.so:system/vendor/lib/mmi_keypadbacklight.so \
    $(VENDOR_PATH)/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
    $(VENDOR_PATH)/vendor/lib/mmi_led.so:system/vendor/lib/mmi_led.so \
    $(VENDOR_PATH)/vendor/lib/mmi_lsensor.so:system/vendor/lib/mmi_lsensor.so \
    $(VENDOR_PATH)/vendor/lib/mmi_msensor.so:system/vendor/lib/mmi_msensor.so \
    $(VENDOR_PATH)/vendor/lib/mmi_psensor.so:system/vendor/lib/mmi_psensor.so \
    $(VENDOR_PATH)/vendor/lib/mmi_sdcard.so:system/vendor/lib/mmi_sdcard.so \
    $(VENDOR_PATH)/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
    $(VENDOR_PATH)/vendor/lib/mmi_touchpanel.so:system/vendor/lib/mmi_touchpanel.so \
    $(VENDOR_PATH)/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
    $(VENDOR_PATH)/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
    $(VENDOR_PATH)/vendor/lib/mmi_volume.so:system/vendor/lib/mmi_volume.so \
    $(VENDOR_PATH)/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so

# vendor/lib/hw
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
    $(VENDOR_PATH)/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so

# vendor/lib/egl
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(VENDOR_PATH)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(VENDOR_PATH)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(VENDOR_PATH)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(VENDOR_PATH)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so
